/**
 ** This file is part of the libgamepad project.
 ** Copyright 2020 univrsal <universailp@web.de>.
 **
 ** This program is free software: you can redistribute it and/or modify
 ** it under the terms of the GNU Lesser General Public License as
 ** published by the Free Software Foundation, either version 3 of the
 ** License, or (at your option) any later version.
 **
 ** This program is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 ** GNU Lesser General Public License for more details.
 **
 ** You should have received a copy of the GNU Lesser General Public License
 ** along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

#include <gamepad/binding-default.hpp>

namespace gamepad {
namespace defaults {
    const char* linux_bind_json = "{"
                                  "\"name\": \"Default Linux binding\","
                                  "\"binds\":"
                                  "["
                                  "{"
                                  "    \"from\": 0,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60416"
                                  "},"
                                  "{"
                                  "    \"from\": 1,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60417"
                                  "},"
                                  "{"
                                  "    \"from\": 2,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60418"
                                  "},"
                                  "{"
                                  "    \"from\": 3,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60419"
                                  "},"
                                  "{"
                                  "    \"from\": 7,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60422"
                                  "},"
                                  "{"
                                  "    \"from\": 6,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60423"
                                  "},"
                                  "{"
                                  "    \"from\": 8,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60424"
                                  "},"
                                  "{"
                                  "    \"from\": 9,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60425"
                                  "},"
                                  "{"
                                  "    \"from\": 10,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60426"
                                  "},"
                                  "{"
                                  "    \"from\": 11,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60427"
                                  "},"
                                  "{"
                                  "    \"from\": 12,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60428"
                                  "},"
                                  "{"
                                  "    \"from\": 13,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60429"
                                  "},"
                                  "{"
                                  "    \"from\": 14,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60430"
                                  "},"
                                  "{"
                                  "    \"from\": 4,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60420"
                                  "},"
                                  "{"
                                  "    \"from\": 5,"
                                  "    \"is_axis\": false,"
                                  "    \"to\": 60421"
                                  "},"
                                  "{"
                                  "    \"from\": 0,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60431"
                                  "},"
                                  "{"
                                  "    \"from\": 1,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60432"
                                  "},"
                                  "{"
                                  "    \"from\": 2,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60433"
                                  "},"
                                  "{"
                                  "    \"from\": 3,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60434"
                                  "},"
                                  "{"
                                  "    \"from\": 4,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60435"
                                  "},"
                                  "{"
                                  "    \"from\": 5,"
                                  "    \"is_axis\": true,"
                                  "    \"to\": 60436"
                                  "}"
                                  "]}";

    const char* dinput_bind_json = "{"
                                   "\"name\": \"Default DirectInput binding\","
                                   "\"binds\": ["
                                   "    {"
                                   "        \"from\": 0,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60416"
                                   "    },"
                                   "    {"
                                   "        \"from\": 1,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60417"
                                   "    },"
                                   "    {"
                                   "        \"from\": 2,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60418"
                                   "    },"
                                   "    {"
                                   "        \"from\": 3,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60419"
                                   "    },"
                                   "    {"
                                   "        \"from\": 6,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60422"
                                   "    },"
                                   "    {"
                                   "        \"from\": 7,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60423"
                                   "    },"
                                   "    {"
                                   "        \"from\": 8,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60425"
                                   "    },"
                                   "    {"
                                   "        \"from\": 9,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60426"
                                   "    },"
                                   "    {"
                                   "        \"from\": 129,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60427"
                                   "    },"
                                   "    {"
                                   "        \"from\": 131,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60428"
                                   "    },"
                                   "    {"
                                   "        \"from\": 128,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60429"
                                   "    },"
                                   "    {"
                                   "        \"from\": 130,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60430"
                                   "    },"
                                   "    {"
                                   "        \"from\": 4,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60420"
                                   "    },"
                                   "    {"
                                   "        \"from\": 5,"
                                   "        \"is_axis\": false,"
                                   "        \"to\": 60421"
                                   "    },"
                                   "    {"
                                   "        \"from\": 0,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60431"
                                   "    },"
                                   "    {"
                                   "        \"from\": 1,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60432"
                                   "    },"
                                   "    {"
                                   "        \"from\": 2,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60433,"
                                   "        \"trigger_polarity\": 1"
                                   "    },"
                                   "    {"
                                   "        \"from\": 3,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60434"
                                   "    },"
                                   "    {"
                                   "        \"from\": 4,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60435"
                                   "    },"
                                   "    {"
                                   "        \"from\": 2,"
                                   "        \"is_axis\": true,"
                                   "        \"to\": 60436,"
                                   "        \"trigger_polarity\": -1"
                                   "    }"
                                   "]}";
    const char* xinput_bind_json = "{"
                                   "  \"name\": \"Default Xinput binding\","
                                   "  \"binds\": ["
                                   "    {"
                                   "      \"from\": 4096,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60416"
                                   "    },"
                                   "    {"
                                   "      \"from\": 8192,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60417"
                                   "    },"
                                   "    {"
                                   "      \"from\": 16384,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60418"
                                   "    },"
                                   "    {"
                                   "      \"from\": 32768,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60419"
                                   "    },"
                                   "    {"
                                   "      \"from\": 32,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60422"
                                   "    },"
                                   "    {"
                                   "      \"from\": 16,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60423"
                                   "    },"
                                   "    {"
                                   "      \"from\": 1024,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60424"
                                   "    },"
                                   "    {"
                                   "      \"from\": 64,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60425"
                                   "    },"
                                   "    {"
                                   "      \"from\": 128,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60426"
                                   "    },"
                                   "    {"
                                   "      \"from\": 4,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60427"
                                   "    },"
                                   "    {"
                                   "      \"from\": 8,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60428"
                                   "    },"
                                   "    {"
                                   "      \"from\": 1,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60429"
                                   "    },"
                                   "    {"
                                   "      \"from\": 2,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60430"
                                   "    },"
                                   "    {"
                                   "      \"from\": 256,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60420"
                                   "    },"
                                   "    {"
                                   "      \"from\": 512,"
                                   "      \"is_axis\": false,"
                                   "      \"to\": 60421"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60431,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60431"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60432,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60432"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60433,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60433"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60434,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60434"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60435,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60435"
                                   "    },"
                                   "    {"
                                   "      \"from\": 60436,"
                                   "      \"is_axis\": true,"
                                   "      \"to\": 60436"
                                   "    }"
                                   "  ]"
                                   "}";
}
}
